use jaspar;
START TRANSACTION;
CREATE TABLE MATRIX (
  ID int NOT NULL AUTO_INCREMENT,
  COLLECTION varchar(16) DEFAULT "",
  BASE_ID varchar(16) NOT NULL DEFAULT "",
  VERSION integer NOT NULL DEFAULT "1",
  NAME varchar(255) NOT NULL DEFAULT "",
  PRIMARY KEY (ID)
);
INSERT INTO
  MATRIX (ID, COLLECTION, BASE_ID, VERSION, NAME)
VALUES
  (9229, "CORE", "MA0001", 1, "AGL3");
COMMIT;
